# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d30882f01bcb1935cacb8f8ef2ffebbe5efc878996701c5c08447a586922f13ca3145603ee021822335fac4a1fb5e3d57c4c1764a7e17d53ac5651100b37b4a0

test:
  secret_key_base: e03963de3d60be4c6273929753634f1c30475dd6615971d4748ac91e6edf44340d4053e6ad56eb0b86ccb1e62e3037974bf9413f94bca67b097c22924d68a58c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
